[thresholds]
frequency_cutoff = 0.0001
homozygous_frequency_cutoff = 0.0001
denovo_frequency_cutoff = 0.000001
spliceai_cutoff = 0.5
# DeepVariant/Glnexus quality scores are better calibrated than the historical
# GATK-based pipeline, so the old very high GQ cutoffs are too strict here.
gq_cutoff = 8.0
gq_hom_cutoff = 5.0
mq_cutoff = -10.0
min_alt_reads = 2
min_denovo_read_fraction = 0.1
splice_acceptor_window = 50
splice_donor_window = 10
extended_cnv_splice_window = 400
gene_distance_cutoff = 2000
manta_gq_cutoff = 20.0
manta_min_total_alt_support = 8
manta_min_sr_alt_support = 2
manta_min_size = 50

[resources]
gtf = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/gencode.v49.annotation.gtf"
]
omim_morbid = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/morbidmap.txt"
]
omim_mim2gene = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/mim2gene.txt"
]
omim_ensg_to_hgnc = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/ensg_to_hgnc.csv"
]
panelapp_genes = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/panelapp_genes.tsv"
]
sample_comments = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/sample_details.tsv"
]
imprinted_genes = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/list"
]
excluded_variants_diag = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/diagnostic_artefacts.tsv"
]
excluded_genes_diag = [
  "/ennis/projects/Research_Project-MRC147594/resources/grch38-v2-pipeline/julia_prioritisation_app/resources/diagnostic_exclude_genes.tsv"
]
